import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { MessageCircle } from "lucide-react";
import "./globals.css";
import Navbar from "@/component/nav";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      
      <body
      
        className={`${poppins.variable} font-sans antialiased`}
      >
        <Navbar/>
        {children}
        <a
          href="https://wa.me/+5493512435151"
          aria-label="Abrir conversación de WhatsApp"
          target="_blank"
          rel="noreferrer noopener"
          className="fixed bottom-6 right-6 z-50 inline-flex items-center gap-2 rounded-full bg-green-500 px-4 py-3 text-white shadow-lg shadow-green-500/30 transition hover:bg-green-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-500 md:bottom-8 md:right-8"
        >
          <MessageCircle className="h-5 w-5" aria-hidden="true" />
          <span className="hidden sm:inline text-sm font-medium">WhatsApp</span>
        </a>
      </body>
    </html>
  );
}
