"use client";

import Footer from "./footer";
import ScrollReveal from "@/component/ScrollReveal";
import { Playfair_Display } from "next/font/google";
import { Check, MapPin, Sparkles } from "lucide-react";
import { NAVY, ACCENT } from "@/lib/theme";

const playfair = Playfair_Display({ subsets: ["latin"], weight: ["400", "500", "600", "700"], style: ["normal", "italic"], variable: "--font-playfair" });

const HERO_IMAGE = "https://res.cloudinary.com/dtmziqubb/image/upload/v1779130092/7922f17c13da4ca87bf634b2dc00f7ef_ktfxmv.jpg";
const GREAT_WALL_IMAGE = "https://res.cloudinary.com/dtmziqubb/image/upload/v1774457172/Rectangle_7_cn7a63.png";
const SHANGHAI_IMAGE = "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1800&q=85";
const CHINA_LANDSCAPE = "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?auto=format&fit=crop&w=1800&q=85";

const route = ["Pekín", "Shanghái", "Luoyang", "Xi'an", "Chengdu", "Zhaoxing", "Chengyang", "Longsheng", "Guilin", "Yangshuo", "Huangyao", "Cantón", "Zhuhai", "Macao", "Hong Kong"];

type Stop = { id: number; title: string; subtitle: string; description?: string; image: string; listTitle: string; items: string[]; recommendation?: string };

const stops: Stop[] = [
  { id: 1, title: "Pekín", subtitle: "El corazón imperial", image: GREAT_WALL_IMAGE, listTitle: "Imprescindibles", items: ["Ciudad Prohibida.", "Plaza de Tiananmén.", "Palacio de Verano.", "Templo del Cielo.", "Gran Muralla China.", "Hutongs."], recommendation: "Dedica un día completo a la Gran Muralla y otro a recorrer los hutongs sin prisas." },
  { id: 2, title: "Shanghái", subtitle: "Lo mejor de la China moderna", image: SHANGHAI_IMAGE, listTitle: "No te pierdas", items: ["El Bund.", "Pudong.", "Jardín Yuyuan.", "Nanjing Road.", "Concesión Francesa."] },
  { id: 3, title: "Luoyang", subtitle: "Historia milenaria", description: "Una de las ciudades históricas más importantes de China e ideal para combinar con Xi'an.", image: CHINA_LANDSCAPE, listTitle: "Imprescindibles", items: ["Grutas de Longmen.", "Templo del Caballo Blanco."] },
  { id: 4, title: "Xi'an", subtitle: "La antigua capital imperial", image: GREAT_WALL_IMAGE, listTitle: "Lo mejor", items: ["Guerreros de Terracota.", "Barrio Musulmán.", "Torre del Tambor.", "Torre de la Campana."] },
  { id: 5, title: "Chengdu", subtitle: "Pandas y gastronomía", description: "Una ciudad con un ambiente relajado y una gastronomía inolvidable.", image: CHINA_LANDSCAPE, listTitle: "Imprescindible", items: ["Base de investigación del panda gigante."] },
  { id: 6, title: "Zhaoxing", subtitle: "Cultura de la etnia dong", description: "Uno de los pueblos dong más bonitos de China. Muy recomendable para conocer la cultura de las minorías étnicas.", image: CHINA_LANDSCAPE, listTitle: "Destacan", items: ["Torres del Tambor.", "Puentes cubiertos.", "Arquitectura tradicional de madera."] },
  { id: 7, title: "Chengyang", subtitle: "Arquitectura tradicional dong", description: "Famoso por el impresionante Puente del Viento y la Lluvia. Una parada perfecta para disfrutar de la arquitectura tradicional dong.", image: CHINA_LANDSCAPE, listTitle: "No te pierdas", items: ["Puente del Viento y la Lluvia.", "Aldeas y construcciones tradicionales dong."] },
  { id: 8, title: "Longsheng", subtitle: "Terrazas de arroz de Longji", description: "Las terrazas de arroz de Longji forman uno de los paisajes más impresionantes del país.", image: CHINA_LANDSCAPE, listTitle: "Lo mejor", items: ["Senderismo.", "Miradores.", "Aldeas tradicionales."] },
  { id: 9, title: "Guilin", subtitle: "Montañas kársticas", description: "Una ciudad rodeada por algunas de las formaciones naturales más características de China.", image: CHINA_LANDSCAPE, listTitle: "Imprescindibles", items: ["Colina de la Trompa de Elefante.", "Pagodas del Sol y la Luna.", "Paseo por el río.", "Gruta de las Flautas de Caña."] },
  { id: 10, title: "Yangshuo", subtitle: "Uno de mis lugares favoritos", description: "Un destino ideal para quienes disfrutan de la naturaleza.", image: CHINA_LANDSCAPE, listTitle: "No te pierdas", items: ["Paseo en bicicleta entre arrozales.", "Río Yulong.", "Crucero por el río Li.", "West Street."] },
  { id: 11, title: "Huangyao", subtitle: "Un pueblo antiguo y tranquilo", description: "Un pueblo con más de mil años de historia, mucho más tranquilo que otros pueblos históricos de China.", image: CHINA_LANDSCAPE, listTitle: "Perfecto para pasear por", items: ["Calles empedradas.", "Canales.", "Casas tradicionales."] },
  { id: 12, title: "Cantón (Guangzhou)", subtitle: "Tradición y modernidad", description: "Una ciudad vibrante donde tradición y modernidad conviven.", image: SHANGHAI_IMAGE, listTitle: "Recomendaciones", items: ["Isla Shamian.", "Torre de Cantón.", "Mercado Qingping.", "Templo de los Seis Banianos.", "Probar el auténtico dim sum."] },
  { id: 13, title: "Hong Kong", subtitle: "El broche final del viaje", image: SHANGHAI_IMAGE, listTitle: "No te pierdas", items: ["Victoria Peak.", "Star Ferry.", "Mercado nocturno de Temple Street.", "Avenida de las Estrellas.", "Monasterio Po Lin y el Gran Buda."] },
];

const tips = ["Consulta los requisitos de visado antes de viajar.", "Lleva instalada una VPN si la necesitas.", "Descarga mapas sin conexión.", "Usa Alipay o WeChat Pay para los pagos.", "Reserva con antelación los trenes de alta velocidad.", "Lleva siempre el pasaporte."];

function FourPointStar({ className = "" }: { className?: string }) { return <svg className={className} viewBox="0 0 24 24" fill="currentColor" aria-hidden><path d="M12 2l2.2 7.8L22 12l-7.8 2.2L12 22l-2.2-7.8L2 12l7.8-2.2L12 2z" /></svg>; }

export default function China() {
  return <div className={`${playfair.variable} min-h-screen bg-[#f8f9fa]`}><ScrollReveal><article className="w-full">
    <section className="relative w-full" aria-label="Portada de la guía de viaje por China"><div className="min-h-[42vh] w-full bg-cover bg-center sm:min-h-[48vh] md:min-h-[56vh] lg:min-h-[62vh]" style={{ backgroundImage: `url("${HERO_IMAGE}")` }} /><div className="absolute inset-0 bg-gradient-to-b from-black/15 to-black/50" /></section>

    <section className="relative z-10 mx-auto -mt-16 max-w-4xl px-4 sm:-mt-20 sm:px-6 md:-mt-24 md:px-8"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full border-4 border-white bg-[#fff8f4] text-5xl shadow-lg sm:h-28 sm:w-28 sm:text-6xl md:h-32 md:w-32"><span role="img" aria-label="Bandera de China">🇨🇳</span></div><div className="mt-4 rounded-2xl bg-white px-5 py-7 text-center shadow-[0_8px_40px_rgba(26,43,76,0.1)] sm:mt-5 sm:rounded-3xl sm:px-8 sm:py-9"><FourPointStar className="mx-auto mb-3 h-2.5 w-2.5 text-[#5D87FF]" /><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.22em]" style={{ color: ACCENT }}>Mi gran recorrido por Asia</p><h1 className={`${playfair.className} font-semibold leading-tight`} style={{ color: NAVY, fontSize: "clamp(1.9rem, 5vw, 3rem)" }}>Guía de viaje por China<span className="block font-normal italic" style={{ color: ACCENT }}>historia, cultura y paisajes inolvidables</span></h1><FourPointStar className="mx-auto my-4 h-3 w-3 text-[#5D87FF]" /><p className="text-sm leading-relaxed text-gray-600 sm:text-base">China es un país inmenso, con una diversidad cultural, histórica y paisajística difícil de igualar. En este viaje recorrí desde las antiguas capitales imperiales hasta pueblos tradicionales, terrazas de arroz, montañas kársticas y algunas de las ciudades más modernas de Asia.</p><div className="mt-7"><div className="mb-3 flex items-center justify-center gap-2 text-xs font-semibold uppercase tracking-[0.16em]" style={{ color: NAVY }}><MapPin className="h-4 w-4" style={{ color: ACCENT }} />La ruta que realicé</div><div className="flex flex-wrap justify-center gap-2">{route.map((place) => <span key={place} className="rounded-full bg-[#f8f9fa] px-3 py-1.5 text-xs text-gray-600">{place}</span>)}</div></div></div></section>

    <section className="mx-auto max-w-5xl space-y-6 px-4 py-10 sm:space-y-8 sm:px-6 sm:py-14 md:px-8 md:py-16">{stops.map((stop) => <section key={stop.id} className="group overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-[0_4px_24px_rgba(26,43,76,0.07)] transition-shadow hover:shadow-[0_8px_32px_rgba(26,43,76,0.12)] sm:rounded-3xl"><div className="aspect-[16/9] w-full bg-cover bg-center transition-transform duration-700 group-hover:scale-[1.02] sm:aspect-[21/9]" style={{ backgroundImage: `url("${stop.image}")` }} role="img" aria-label={stop.title} /><div className="bg-white px-5 py-6 sm:px-7 sm:py-7 md:px-8 md:py-8"><p className="text-[10px] font-semibold uppercase tracking-[0.2em]" style={{ color: ACCENT }}>Parada {stop.id}</p><h2 className={`${playfair.className} mt-1 text-2xl font-semibold sm:text-3xl`} style={{ color: NAVY }}>{stop.title}</h2><p className={`${playfair.className} mt-1 italic text-gray-500`}>{stop.subtitle}</p>{stop.description && <p className="mt-4 text-sm leading-relaxed text-gray-700 sm:text-base">{stop.description}</p>}<div className="mt-6 border-t border-gray-100 pt-5"><h3 className="text-xs font-semibold uppercase tracking-[0.14em]" style={{ color: NAVY }}>{stop.listTitle}</h3><ul className="mt-3 grid gap-2.5 text-sm text-gray-600 sm:grid-cols-2">{stop.items.map((item) => <li key={item} className="flex items-start gap-2.5"><Check className="mt-0.5 h-4 w-4 shrink-0" style={{ color: ACCENT }} /><span>{item}</span></li>)}</ul></div>{stop.recommendation && <div className="mt-5 flex items-start gap-3 rounded-xl bg-[#fffaf1] px-4 py-4 text-sm leading-relaxed text-gray-600"><Sparkles className="mt-0.5 h-4 w-4 shrink-0" style={{ color: ACCENT }} /><p><strong style={{ color: NAVY }}>Mi recomendación:</strong> {stop.recommendation}</p></div>}</div></section>)}</section>

    <section className="mx-auto max-w-4xl px-4 pb-14 sm:px-6 sm:pb-20 md:px-8"><div className="rounded-2xl border border-[#5D87FF]/15 bg-white px-5 py-7 shadow-[0_4px_24px_rgba(26,43,76,0.07)] sm:rounded-3xl sm:px-8 sm:py-9"><div className="flex items-center gap-3"><Sparkles className="h-5 w-5" style={{ color: ACCENT }} /><h2 className={`${playfair.className} text-2xl font-semibold sm:text-3xl`} style={{ color: NAVY }}>Recomendaciones para viajar por China</h2></div><ul className="mt-6 grid gap-3 text-sm leading-relaxed text-gray-600 sm:grid-cols-2">{tips.map((tip) => <li key={tip} className="flex items-start gap-2.5"><Check className="mt-0.5 h-4 w-4 shrink-0" style={{ color: ACCENT }} /><span>{tip}</span></li>)}</ul></div></section>
  </article></ScrollReveal><Footer /></div>;
}
