"use client";

import Footer from "./footer";
import ScrollReveal from "@/component/ScrollReveal";
import { Playfair_Display } from "next/font/google";
import { Check, MapPin, Sparkles } from "lucide-react";
import { NAVY, ACCENT } from "@/lib/theme";

const playfair = Playfair_Display({ subsets: ["latin"], weight: ["400", "500", "600", "700"], style: ["normal", "italic"], variable: "--font-playfair" });

const HERO_IMAGE = "https://res.cloudinary.com/dtmziqubb/image/upload/v1783706743/Mejora_imagen_sin_modificar_cara_202607081613_2_fz6smk.jpg";
const TAJ_IMAGE = "https://res.cloudinary.com/dtmziqubb/image/upload/v1777483590/22685_s0blke.jpg";
const INDIA_CITY = "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1800&q=85";
const RAJASTHAN_IMAGE = "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1800&q=85";
const VARANASI_IMAGE = "https://images.unsplash.com/photo-1561361058-c24e02d8e942?auto=format&fit=crop&w=1800&q=85";

const route = ["Delhi", "Bikaner", "Agra", "Varanasi", "Jaisalmer", "Jodhpur", "Udaipur", "Jaipur"];

type Stop = { id: number; title: string; subtitle: string; description: string; image: string; listTitle: string; items: string[]; advice?: string; closing?: string };

const stops: Stop[] = [
  { id: 1, title: "Delhi", subtitle: "Tradición y modernidad", description: "Delhi suele ser la puerta de entrada al país y representa perfectamente el contraste entre tradición y modernidad. Sus calles están llenas de vida, mercados, templos, mezquitas y monumentos históricos.", image: INDIA_CITY, listTitle: "Qué no te puedes perder", items: ["Fuerte Rojo.", "Jama Masjid.", "India Gate.", "Tumba de Humayun.", "Qutub Minar.", "Chandni Chowk y su famoso mercado."], advice: "Reserva al menos dos o tres días para adaptarte al ritmo del país antes de continuar el viaje." },
  { id: 2, title: "Bikaner", subtitle: "El Rajastán más auténtico", description: "Bikaner es una de las ciudades menos turísticas del Rajastán, pero merece mucho la pena. Conserva un ambiente auténtico y uno de los fuertes mejor conservados de la región.", image: RAJASTHAN_IMAGE, listTitle: "Imprescindibles", items: ["Fuerte Junagarh.", "Palacio Lalgarh.", "Mercado antiguo.", "Templo de Karni Mata, el famoso templo de las ratas, situado a unos kilómetros de la ciudad."] },
  { id: 3, title: "Agra", subtitle: "Mucho más que el Taj Mahal", description: "Aunque el Taj Mahal es el gran protagonista, Agra tiene mucho más que ofrecer.", image: TAJ_IMAGE, listTitle: "Qué visitar", items: ["Taj Mahal al amanecer.", "Fuerte de Agra.", "Mehtab Bagh, desde donde se obtienen vistas espectaculares del Taj Mahal."], advice: "Compra las entradas con antelación para evitar largas colas." },
  { id: 4, title: "Varanasi", subtitle: "La ciudad espiritual de la India", description: "Varanasi es una de las ciudades habitadas más antiguas del mundo y el corazón espiritual del hinduismo. Es un lugar que impacta profundamente y donde la vida y la muerte conviven junto al río Ganges.", image: VARANASI_IMAGE, listTitle: "Experiencias imprescindibles", items: ["Paseo en barca al amanecer.", "Ceremonia Ganga Aarti al atardecer.", "Recorrer los ghats.", "Perderse por sus callejuelas."], closing: "Es una ciudad intensa, pero también una de las más auténticas del país." },
  { id: 5, title: "Jaisalmer", subtitle: "La ciudad dorada", description: "En pleno desierto del Thar aparece Jaisalmer, conocida como la Ciudad Dorada por el color de su piedra.", image: RAJASTHAN_IMAGE, listTitle: "Qué hacer", items: ["Visitar el fuerte viviente de Jaisalmer.", "Descubrir sus havelis.", "Pasear por sus mercados.", "Dormir en un campamento en el desierto.", "Hacer una excursión en camello al atardecer."], closing: "Sin duda, una de las experiencias más especiales del viaje." },
  { id: 6, title: "Jodhpur", subtitle: "La ciudad azul", description: "Jodhpur destaca por sus casas pintadas de azul y por uno de los fuertes más impresionantes de toda la India.", image: RAJASTHAN_IMAGE, listTitle: "No te pierdas", items: ["Fuerte Mehrangarh.", "Jaswant Thada.", "Torre del Reloj.", "Mercado Sardar."], closing: "Subir al fuerte permite disfrutar de unas vistas increíbles sobre toda la ciudad." },
  { id: 7, title: "Udaipur", subtitle: "La ciudad de los lagos", description: "Después del bullicio de otras ciudades, Udaipur ofrece un ambiente mucho más tranquilo y romántico.", image: RAJASTHAN_IMAGE, listTitle: "Lugares imprescindibles", items: ["City Palace.", "Lago Pichola.", "Paseo en barco al atardecer.", "Templo Jagdish.", "Palacio del Monzón."], closing: "Es uno de los destinos más elegantes del Rajastán." },
  { id: 8, title: "Jaipur", subtitle: "La ciudad rosa", description: "Jaipur es una mezcla perfecta de historia, arquitectura y cultura. Es una de las ciudades más visitadas del Triángulo Dorado.", image: RAJASTHAN_IMAGE, listTitle: "Qué visitar", items: ["Fuerte Amber.", "Palacio de los Vientos (Hawa Mahal).", "City Palace.", "Jantar Mantar.", "Mercado Bapu Bazaar."], advice: "No olvides probar la gastronomía local y dedicar tiempo a recorrer sus bazares." },
];

const tips = ["Lleva ropa cómoda y ligera, pero respetuosa con la cultura local.", "Bebe siempre agua embotellada.", "Contrata un seguro de viaje.", "Lleva efectivo para pequeñas compras.", "Negocia los precios en muchos mercados, ya que forma parte de la cultura.", "Mantén una actitud abierta: la India es un país que se vive con todos los sentidos."];

function FourPointStar({ className = "" }: { className?: string }) { return <svg className={className} viewBox="0 0 24 24" fill="currentColor" aria-hidden><path d="M12 2l2.2 7.8L22 12l-7.8 2.2L12 22l-2.2-7.8L2 12l7.8-2.2L12 2z" /></svg>; }

export default function India() {
  return <div className={`${playfair.variable} min-h-screen bg-[#f8f9fa]`}><ScrollReveal><article className="w-full">
    <section className="relative w-full" aria-label="Portada de la guía de viaje por la India"><div className="min-h-[42vh] w-full bg-cover bg-center sm:min-h-[48vh] md:min-h-[56vh] lg:min-h-[62vh]" style={{ backgroundImage: `url("${HERO_IMAGE}")` }} /><div className="absolute inset-0 bg-gradient-to-b from-black/15 to-black/50" /></section>

    <section className="relative z-10 mx-auto -mt-16 max-w-4xl px-4 sm:-mt-20 sm:px-6 md:-mt-24 md:px-8"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full border-4 border-white bg-[#fff9f2] text-5xl shadow-lg sm:h-28 sm:w-28 sm:text-6xl md:h-32 md:w-32"><span role="img" aria-label="Bandera de India">🇮🇳</span></div><div className="mt-4 rounded-2xl bg-white px-5 py-7 text-center shadow-[0_8px_40px_rgba(26,43,76,0.1)] sm:mt-5 sm:rounded-3xl sm:px-8 sm:py-9"><FourPointStar className="mx-auto mb-3 h-2.5 w-2.5 text-[#5D87FF]" /><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.22em]" style={{ color: ACCENT }}>Mi recorrido por el norte del país</p><h1 className={`${playfair.className} font-semibold leading-tight`} style={{ color: NAVY, fontSize: "clamp(1.9rem, 5vw, 3rem)" }}>Guía de viaje a la India<span className="block font-normal italic" style={{ color: ACCENT }}>un viaje que me cambió por completo</span></h1><FourPointStar className="mx-auto my-4 h-3 w-3 text-[#5D87FF]" /><p className="text-sm leading-relaxed text-gray-600 sm:text-base">La India es un país que no deja indiferente a nadie. Es intensa, caótica, espiritual, colorida y sorprendente. Cada ciudad tiene una personalidad única. En este viaje recorrí algunos de los destinos más emblemáticos del norte, descubriendo palacios, fuertes, templos, desiertos y una cultura fascinante.</p><p className="mt-4 text-sm leading-relaxed text-gray-600 sm:text-base">La India no es un viaje cualquiera; es una experiencia que transforma la forma de ver el mundo. Si estás planeando un viaje similar, esta ruta puede servirte como inspiración.</p><div className="mt-7"><div className="mb-3 flex items-center justify-center gap-2 text-xs font-semibold uppercase tracking-[0.16em]" style={{ color: NAVY }}><MapPin className="h-4 w-4" style={{ color: ACCENT }} />La ruta que recorrí</div><div className="flex flex-wrap justify-center gap-2">{route.map((place) => <span key={place} className="rounded-full bg-[#f8f9fa] px-3 py-1.5 text-xs text-gray-600">{place}</span>)}</div></div></div></section>

    <section className="mx-auto max-w-5xl space-y-6 px-4 py-10 sm:space-y-8 sm:px-6 sm:py-14 md:px-8 md:py-16">{stops.map((stop) => <section key={stop.id} className="group overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-[0_4px_24px_rgba(26,43,76,0.07)] transition-shadow hover:shadow-[0_8px_32px_rgba(26,43,76,0.12)] sm:rounded-3xl"><div className="aspect-[16/9] w-full bg-cover bg-center transition-transform duration-700 group-hover:scale-[1.02] sm:aspect-[21/9]" style={{ backgroundImage: `url("${stop.image}")` }} role="img" aria-label={stop.title} /><div className="bg-white px-5 py-6 sm:px-7 sm:py-7 md:px-8 md:py-8"><p className="text-[10px] font-semibold uppercase tracking-[0.2em]" style={{ color: ACCENT }}>Parada {stop.id}</p><h2 className={`${playfair.className} mt-1 text-2xl font-semibold sm:text-3xl`} style={{ color: NAVY }}>{stop.title}</h2><p className={`${playfair.className} mt-1 italic text-gray-500`}>{stop.subtitle}</p><p className="mt-4 text-sm leading-relaxed text-gray-700 sm:text-base">{stop.description}</p><div className="mt-6 border-t border-gray-100 pt-5"><h3 className="text-xs font-semibold uppercase tracking-[0.14em]" style={{ color: NAVY }}>{stop.listTitle}</h3><ul className="mt-3 grid gap-2.5 text-sm text-gray-600 sm:grid-cols-2">{stop.items.map((item) => <li key={item} className="flex items-start gap-2.5"><Check className="mt-0.5 h-4 w-4 shrink-0" style={{ color: ACCENT }} /><span>{item}</span></li>)}</ul></div>{stop.advice && <div className="mt-5 flex items-start gap-3 rounded-xl bg-[#fffaf1] px-4 py-4 text-sm leading-relaxed text-gray-600"><Sparkles className="mt-0.5 h-4 w-4 shrink-0" style={{ color: ACCENT }} /><p><strong style={{ color: NAVY }}>Consejo:</strong> {stop.advice}</p></div>}{stop.closing && <p className={`${playfair.className} mt-5 border-l-2 pl-4 italic leading-relaxed text-gray-600`} style={{ borderColor: ACCENT }}>{stop.closing}</p>}</div></section>)}</section>

    <section className="mx-auto max-w-4xl px-4 pb-12 sm:px-6 sm:pb-16 md:px-8"><div className="rounded-2xl border border-[#5D87FF]/15 bg-white px-5 py-7 shadow-[0_4px_24px_rgba(26,43,76,0.07)] sm:rounded-3xl sm:px-8 sm:py-9"><div className="flex items-center gap-3"><Sparkles className="h-5 w-5" style={{ color: ACCENT }} /><h2 className={`${playfair.className} text-2xl font-semibold sm:text-3xl`} style={{ color: NAVY }}>Consejos para viajar por la India</h2></div><ul className="mt-6 grid gap-3 text-sm leading-relaxed text-gray-600 sm:grid-cols-2">{tips.map((tip) => <li key={tip} className="flex items-start gap-2.5"><Check className="mt-0.5 h-4 w-4 shrink-0" style={{ color: ACCENT }} /><span>{tip}</span></li>)}</ul></div></section>

    <section className="mx-auto max-w-3xl px-4 pb-14 text-center sm:px-6 sm:pb-20 md:px-8"><FourPointStar className="mx-auto mb-5 h-4 w-4 text-[#5D87FF]" /><p className={`${playfair.className} text-base italic leading-relaxed text-gray-600 sm:text-lg`}>Prepárate para vivir una aventura inolvidable llena de historia, cultura, colores y momentos que recordarás para siempre.</p></section>
  </article></ScrollReveal><Footer /></div>;
}
